name: handgesture
description: "Final Year Project - Hand Gesture Recognition using MediaPipe"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  model_viewer_plus: ^1.7.0

  # --- THE AI & CAMERA STACK ---
  hand_landmarker: ^3.0.1
  google_mlkit_pose_detection: ^0.15.0
  camera: ^0.12.0+1
  permission_handler: ^11.3.1
  path_provider: ^2.1.2
  cloud_firestore: ^6.4.0
  flutter_tts: ^4.2.2
  share_plus: ^10.1.3
  speech_to_text: ^7.5.0
  supabase_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/translate.png
    - assets/speak.png
    - assets/dictionary.png
    - assets/hand_landmarker.task
    - assets/3D/timmy_final.glb
    - assets/3D/timmy_bagus.glb
    - assets/3D/timmy_aman.glb
    - assets/3D/timmy_hai.glb
    - assets/3D/timmy_sana.glb
    - assets/3D/timmy_anda.glb
    - assets/3D/timmy_diam.glb
    - assets/3D/timmy_apa.glb
    - assets/3D/timmy_fikir.glb
    - assets/3D/timmy_beli.glb
    - assets/3D/timmy_belanja.glb
    - assets/3D/timmy_saya.glb
    - assets/3D/timmy_minum.glb
    - assets/3D/aj_oh.glb
    - assets/3D/timmy_oh.glb
    - assets/3D/timmy_awak.glb
    - assets/3D/timmy_berhenti1.glb
    - assets/3D/timmy_maaf.glb
    - assets/3D/timmy_mana.glb
    - assets/3D/timmy_boleh.glb
    - assets/3D/timmy_tidakboleh.glb
    - assets/3D/timmy_sama-sama.glb
    - assets/3D/timmy_benang1.glb
    - assets/gestures/
    - assets/record.png
    - assets/avatar.png